SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GEOMETRY = f"{SCREEN_WIDTH}x{SCREEN_HEIGHT}+0+0"


CENTRAL_FRAME_WIDTH = 800
CENTRAL_FRAME_HEIGHT = 600
CENTRAL_FRAME_GEOMETRY = f"{CENTRAL_FRAME_WIDTH}x{CENTRAL_FRAME_HEIGHT}"

INTERNAL_FRAME_WIDTH = 600
INTERNAL_FRAME_HEIGHT = 400
INTERNAL_FRAME_GEOMETRY = f"{INTERNAL_FRAME_WIDTH}x{INTERNAL_FRAME_HEIGHT}"

BUTTON_WIDTH = 200
BUTTON_HEIGHT = 80

ENTRY_JUSTIFY = "center"
ENTRY_WIDTH = 200
ENTRY_HEIGHT = 80